spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://ep-icy-forest-a9tzwuqp-pooler.gwc.azure.neon.tech/restfood?sslmode=require
spring.datasource.username=restfood_owner
spring.datasource.password=npg_76tgRLxjieVb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

