spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
restfoods.app.jwtSecret=SehrSicheresUndMindestens64ZeichenLang3ghf83g0hf3ghf03hf9f08ghf0gh
restfoods.app.jwtExpirationMs=86400000

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
