spring.application.name=rest-foods-backend-2-2024
spring.datasource.url=jdbc:postgresql://localhost:5432/fooddb
spring.datasource.username=postgres
spring.datasource.password=deinPasswort
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
